### PR TITLE
Each instance of logger has different TraceID

### PR DESCRIPTION
**Pull request by zimnx**
Because logger Clone literally cloned object, same environment was always passed to logger. This resulted that each logger had same traceID. Now Clone generates new traceID for each instance.

### CODE REVIEW

**Comment by morrisson** [comment]
Thank you for bringing up this issue. This patch can resolve this logger issue, but I think this issue is occurred by a `Environment.Clone()` logic problem. Here is a Clone method in `extension/goplugin/environment.go`.

```
// Clone makes a clone of the rawEnvironment
func (env *Environment) Clone() extension.Environment {
	clone := &Environment{
		initFns:         env.initFns,
		beforeStartHook: env.beforeStartHook,
		afterStopHook:   env.afterStopHook,

		coreImpl:     env.coreImpl.Clone(),
		loggerImpl:   env.loggerImpl.Clone(),
		schemasImpl:  env.schemasImpl.Clone(),
		syncImpl:     env.syncImpl.Clone(),
		databaseImpl: env.databaseImpl.Clone(),

		name: env.name,

		traceID: newTraceID(),

		handlers:       deepcopy.Copy(env.handlers).(EventPrioritizedHandlers),
		schemaHandlers: deepcopy.Copy(env.schemaHandlers).(EventSchemaPrioritizedSchemaHandlers),

		rawTypes: make(map[string]reflect.Type),
		types:    make(map[string]reflect.Type),
	}
	for k, v := range env.rawTypes {
		clone.rawTypes[k] = v
	}
	for k, v := range env.types {
		clone.types[k] = v
	}
	return clone
}
```

Each core, logger, schemas, sync and database type needs to have a relation with parent env. However, each type has a Clone logic like this

```
// Clone allocates a clone of Core; object may be nil
func (core *Core) Clone() *Core {
	if core == nil {
		return nil
	}
	return &Core{
		env: core.env,
	}
}
```

That is, if `e2` is cloned from `e1`,  `e2.coreImpl.env` is `e1`. This is the root problem behind this issue.

Therefore, proper fix should be changing the logic of `Environment.Clone` as follows:

```
func (env *Environment) Clone() extension.Environment {
	clone := &Environment{
		initFns:         env.initFns,
		beforeStartHook: env.beforeStartHook,
		afterStopHook:   env.afterStopHook,

		name: env.name,

		traceID: newTraceID(),

		handlers:       deepcopy.Copy(env.handlers).(EventPrioritizedHandlers),
		schemaHandlers: deepcopy.Copy(env.schemaHandlers).(EventSchemaPrioritizedSchemaHandlers),

		rawTypes: make(map[string]reflect.Type),
		types:    make(map[string]reflect.Type),
	}

	clone.SetCore(env.coreImpl.Clone(clone))
	...

	return clone
}
```

**Comment by zimnx** [comment]
@morrisson Thanks for bringing this. I've added new commit. Objects which are coupled with environment now accept env as argument in Clone method.

**Comment by morrisson** [comment]
Thanks for updating. However, this change is a bit different from what I suggests. I think, traceID should be in Environment then Logger should refer parent environment's traceID because traceID is a kind of identifier of one independent process, that is to say, environment. Logger should just provide a logging feature.

**Comment by zimnx** [comment]
@morrisson I've applied your remarks and squashed commits.

**Pull request merged**
