### PR TITLE
Add missing synchro, fix races and fix leaking goroutine in otto sync builtins

### PR DESCRIPTION
**Pull request by przemyslaw-dobrowolski-cl**
Fix invalid implementation of Sync builtins:
* add missing synchronization (WaitGroup)
* fix races on error variables
* fix leaking goroutine in gohan_sync_watch builtin

### CODE REVIEW

**Comment by morrisson** [comment]
@yudai could you take a look at it?

**Comment by marcin-ptaszynski** [comment]
Resolved by #581

**Comment by przemyslaw-dobrowolski-cl** [comment]
@marcin-ptaszynski This commit addressed three different problems in the implementation. Instead of immediately closing this PR I'd prefer to see any comments or complaints and have a chance to address them.

The merged PR #581 **does not resolve** all the problems, and there are still race conditions in code.

By immediately closing this PR is was clearly signaled that this PR is worthless. In fact, it's not. I'd rather see meaningful discussions about future PRs.

**Comment by marcin-ptaszynski** [comment]
@przemyslaw-dobrowolski-cl , apologies for rushing into it, but we needed to deliver those fixes quickly and PR #581 solved it in much simpler way. Even though race on write err is completely harmless, it still exists, so sorry for closing this PR prematurely.

**Pull request closed without merging**
