### PR TITLE
[CW-5256] Updated middleware API response payload logging level

### PR DESCRIPTION
**Pull request by markstephensntti3io**
Change of logging level for response payload, as requested by Ryota.

### CODE REVIEW

**Comment by alecchepkin** [comment]
test it, please

**Comment by hashimotor** [comment]
lgtm but it seems a draft state

**Review by jpazdyga — APPROVED** [review]

**Review by hashimotor — APPROVED** [review]
LGTM

**Review by hashimotor — APPROVED** [review]

**Comment by markstephensntti3io** [comment]
Hi @yoichi-cloudwan are you able to review?  thank you

**Review by jpazdyga — APPROVED** [review]

**Pull request merged**
