### PR TITLE
support text/plain data

### PR DESCRIPTION
**Pull request by yokoi-h**
- send text/plain data from gohan_http if the content-type is "text/plain"

### CODE REVIEW

**Comment by yokoi-h** [comment]
thank you for your comment. I fixed it.

**Comment by nati** [comment]
LGTM but could you rebase multiple commit for one?

**Comment by nati** [comment]
could you also add unit test for this?
I think we can run web server in the test.

**Comment by yokoi-h** [comment]
Thank you.
I'll add test case and rebase.

**Pull request closed without merging**
