### PR TITLE
Added tags to openapi documentation

### PR DESCRIPTION
**Pull request by michalzurawski**
This will add tags based on resource_group field.

Have a question about this commit:
As you see now it's turn on by default - should I add some flag to enable it only when the flag is given?
And probably split-by-resource will now be redundant as this option allows to create categories in a single json file.

### CODE REVIEW

**Comment by nati** [comment]
resource_group tag should be documented, and you should check if a schema has this or not.
Current code may add a tag with "".

**Comment by michalzurawski** [comment]
Thanks, @nati for that notes.
Have an additional question: how to "compile" this templates for Openapi? It seems that even if completely new Gohan is installed it still uses the old template file.

**Comment by nati** [comment]
Have you done  this?

``` shell
make gen
```

We are using [go-bindata](https://github.com/jteeuwen/go-bindata) and converting template file for go binary. 
You can also manually specify template by command.

**Comment by michalzurawski** [comment]
Thanks a lot `make gen` is exactly what I was looking for.
I knew about `--template` option but it was rather inconvenient.

**Comment by michalzurawski** [comment]
@Zimnx @przemyslaw-dobrowolski-cl @p-kozlowski @marcin-ptaszynski @mmatczuk Please review.

**Comment by przemyslaw-dobrowolski-cl** [comment]
@nati could you take a look at this PR?

**Comment by thayashi** [comment]
@nati pls take a look this PR

**Comment by nati** [comment]
got it

**Comment by thayashi** [comment]
@nati thanks!

**Pull request merged**
