### PR TITLE
gohan_db_transaction isolation level argument

### PR DESCRIPTION
**Pull request by marcin-ptaszynski**
It's not possible to use tx.SetIsolationLevel from otto because of
type mismatch (string vs transaction.Type). This commit allows passing
optional isolation level argument to gohan_db_transaction builtin.

Additional test changes:
 - add golang provided mock library
   (current library is no longer supported)
 - extend transaction mock with SetIsolationLevel
 - add DB mock

### CODE REVIEW

**Comment by nati** [comment]
LGTM but we are investigating CI issue

**Comment by nati** [comment]
CI get fixed, so could you push this branch again if you need to rebase or recreate pull request?

**Comment by nati** [comment]
CI get fixed, so could you push this branch again if you need to rebase or recreate pull request?

**Comment by marcin-ptaszynski** [comment]
Done.

**Comment by przemyslaw-dobrowolski-cl** [comment]
@nati a kind remainder about this PR

**Pull request merged**
