### PR TITLE
Mark a test that was never run and fails as pending

### PR DESCRIPTION
**Pull request by p-kozlowski**
This test was never run on the CI (example: https://circleci.com/gh/cloudwan/gohan/1171?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, look for ok  	github.com/cloudwan/gohan/extension/golang	1.023s	coverage: 0.0% of statements [no tests to run]" in "make test"). When I've enabled it, it always fails.

For now, let's run the suite, but mark the test case as "pending".

Reviewers, what's your opinion about it? Should we fix this test or is it safe to delete?

### CODE REVIEW

**Comment by przemyslaw-dobrowolski-cl** [comment]
If this test may be trivially fixed, then it should be fixed in this PR. Otherwise it should be dropped because it is useless.

**Comment by przemyslaw-dobrowolski-cl** [comment]
@p-kozlowski Lets add Pit for this test, similarly to 3 != 4 test.

**Comment by p-kozlowski** [comment]
reviewers, gentle reminder about this PR. how do you feel about this change?

**Comment by przemyslaw-dobrowolski-cl** [comment]
@morrisson @marcin-ptaszynski @zimnx please review

**Pull request closed without merging**
