### PR TITLE
Add gohan_config built-in

### PR DESCRIPTION
**Pull request by vozhyk-**
- Refactor built-ins' argument parsing
    This refactor includes:

    1. Strict and consistent checking of types in builtin functions arguments - creating functions for them
    2. Extracting non-otto code from builtin functions to test them better
    3. Making builtin functions code cleaner to easily implement new functions
    4. Fixing bugs:
        - not all functions create transaction when passed null
- Add `gohan_config` built-in

### CODE REVIEW

**Comment by kwapik** [comment]
LGTM :+1:

**Comment by nati** [comment]
Could you rebase commit into master?

**Comment by vozhyk-** [comment]
@nati Done.

**Comment by nati** [comment]
thx

**Pull request merged**
