### PR TITLE
Update README for some additional clarity and grammar

### PR DESCRIPTION
**Pull request by leifmadsen**
Take documentation from issue #28 branch and merge it back down into master. I think I'm going to abandon issue 28 in favour of just some updated documentation to make building without a Makefile more clear.

### CODE REVIEW

**Comment by nati** [comment]
Thanks! Forgive us to take a time to prepare CLA stuff.

**Comment by leifmadsen** [comment]
@nati what was the blocker on this again? Thanks!

**Comment by nati** [comment]
@leifmadsen   DOC looks super nice. But, We need prepare contributor license agreement for this project and our Laywer is checking it... Sorry for inconvenience.

**Comment by leifmadsen** [comment]
Ahhh gotcha. Sorry, my brain didn't figure out what CLA meant at first :)

**Comment by nati** [comment]
my bad.. Laywer is still need time to review CLA.. 
BTW, do you mind if I ask to add your name in contributors in this commit?

**Comment by leifmadsen** [comment]
@nati sure name is Leif Madsen, email leif@leifmadsen.com

**Comment by nati** [comment]
Thanks!

**Comment by nati** [comment]
I'm so sorry for talking super long time for this one.

Could you please sign our CLA and send scan for info@cloudwan.io ?

(Individual version) https://github.com/cloudwan/gohan/blob/master/docs/cla.txt
(Company version) https://github.com/cloudwan/gohan/blob/master/docs/ccla.txt

Thanks
Best

**Pull request merged**
