### PR TITLE
Support embed contents using go-bindata

### PR DESCRIPTION
**Pull request by nati**
Closes: #59

### CODE REVIEW

**Comment by yokoi-h** [comment]
I tried to build branch feature/issue59, but compile error occurred.

```
% go build
# github.com/cloudwan/gohan/util
util/util.go:151: undefined: Asset
util/util.go:156: undefined: Asset
```

Is there any missing file?

**Comment by nati** [comment]
you need to use make because ginlog command may generate code

**Comment by yokoi-h** [comment]
Thank you.

I was able to build gohan with make.
But error messages were shown when I started gohan server.
```
% make
% go build
% ./gohan server                                                                                                                                     
13:28:31.322 gohan.server INFO  logging initialized
13:28:31.323 gohan.server INFO  TLS enabled
13:28:31.325 gohan.schema INFO  Loading schema embed://etc/schema/gohan.json ...
13:28:31.327 gohan.schema INFO  Loading schema embed://extensions/gohan_extension.yaml ...
13:28:31.327 gohan.server CRITICAL  invalid schema: Asset extensions/gohan_extension.yaml not found
```

**Comment by nati** [comment]
Thanks. I found a mistake in the config. fixed

**Comment by yokoi-h** [comment]
Thank you.

I was able to embed my schema. It looks good to me.
However I was not able to find a relation between this feature and the deletion of uuid.js and url.js.
Is the deletion related to this feature?

**Comment by nati** [comment]
ya it's unrelated nit fix.
Thank you for review. I'll merge this

**Pull request merged**
