### PR TITLE
Support for schema list relative path

### PR DESCRIPTION
**Pull request by abonie**
Before SCHEMA_INCLUDES used relative path to test file,
which would not work if tests had been placed in different
hierarchies.

### CODE REVIEW

**Comment by marcin-ptaszynski** [comment]
technically, it's support for schema list relative path.

**Comment by marcin-ptaszynski** [comment]
requires some test cases.

**Comment by nati** [comment]
CI get fixed, so could you push this branch again if you need to rebase or recreate pull request?

**Comment by nati** [comment]
CI get fixed, so could you push this branch again if you need to rebase or recreate pull request?

**Pull request merged**
